### ISSUE TITLE
more detailed build instructions?

### ISSUE THREAD

**Issue by jpcoblentz** [microsoft/SparseSC#28]
would you perhaps be able to write more detailed build instructions? my build is consistiently failing every time and I'm not sure why

**Comment by bquistorff** [comment]
It's the typical `python setup.py bdist_wheel` (in the `makefile`). What error are you getting?

**Comment by jpcoblentz** [comment]
it runs, but then when I run the test it returns
```

Jacobs-MacBook-Air:SparseSC jacobcoblentz$ python3 example-code.py

Traceback (most recent call last):

  File "example-code.py", line 13, in <module>

    import SparseSC as SC

ModuleNotFoundError: No module named 'SparseSC'

Jacobs-MacBook-Air:SparseSC jacobcoblentz$

```

**Comment by bquistorff** [comment]
The package has to be installed after it's been built. This will depend on your environment, but the simplest way is `pip install XXXX.whl`.

**Comment by jpcoblentz** [comment]
thanks so much and apologies for this question!
