### ISSUE TITLE
Fix NameError in estimate_effects

### ISSUE THREAD

**Issue by wofein** [microsoft/SparseSC#36]
Hello! 

I believe that the variable name change introduced in this [commit](https://github.com/microsoft/SparseSC/commit/d78c72cbaafbfb5745711119032c982355e0b799) also introduced a bug. The variable was renamed from `cv_folds` to `cf_folds` but there are still two instances of `cv_folds` in `estimate_effects`. This is causing a NameError. I have also added a PR if you want to just change to the new name: https://github.com/microsoft/SparseSC/pull/35

**Comment by bquistorff** [comment]
Hey, thanks for reporting this! Your PR was missing another instance of the renamed variable so I pushed through my own commit.
