### ISSUE TITLE
Confidence Interval in utils.metrics_utils.py breaks

### ISSUE THREAD

**Issue by tom-flamelit** [microsoft/SparseSC#45]
Line number of issue: https://github.com/microsoft/SparseSC/blob/3c0f1938520e7dcaf42eef02cc803a00f46770c6/src/SparseSC/utils/metrics_utils.py#L235

Current situation:
`N0 = 107, N1 = 305` results in a very large `alpha_ind` value in line 295. This exceeds the value of `0.5*(n_pl-1)` in  resulting in line 302 for `outside_avg_effect` being outside of bounds. 

The major issue is the calculation of `p2min = 2/n_pl`

**Comment by bquistorff** [comment]
Thanks for finding this issue! I've fixed it in acd2ad1.
